Repository toolbox-team/reddit-moderator-toolbox, pull requests merged in 2020-03, with the labels that each got.

#244 Standardize JSDoc formatting
  CONTRIBUTING.md
  extension/data/tbapi.js
  extension/data/tbcore.js
  extension/data/tbhelpers.js
  extension/data/tblog.js
  extension/data/tbui.js
Labels: code quality

#242 Get rid of all jQuery array helpers
  extension/data/modules/historybutton.js
  extension/data/modules/macros.js
  extension/data/modules/modbar.js
  extension/data/modules/modbutton.js
  extension/data/modules/modmailpro.js
  extension/data/modules/modmatrix.js
  extension/data/modules/notifier.js
  extension/data/modules/personalnotes.js
  extension/data/modules/profile.js
  extension/data/modules/queuetools.js
  extension/data/modules/usernotes.js
  extension/data/tbcore.js
  extension/data/tbmodule.js
  extension/data/tbui.js
Labels: code quality

#245 Promisify helpers
  extension/data/modules/betterbuttons.js
  extension/data/modules/config.js
  extension/data/modules/domaintagger.js
  extension/data/modules/historybutton.js
  extension/data/modules/macros.js
  extension/data/modules/modbutton.js
  extension/data/modules/notifier.js
  extension/data/modules/nukecomments.js
  extension/data/modules/personalnotes.js
  extension/data/modules/queuetools.js
  extension/data/modules/removalreasons.js
  extension/data/modules/usernotes.js
  extension/data/tbapi.js
  extension/data/tbcore.js
  extension/data/tbui.js
Labels: code quality

#243 Misc. code cleanup stuff (#243) (rip isOdd)
  extension/data/modules/metricstab.js
  extension/data/modules/modbutton.js
  extension/data/modules/modmatrix.js
  extension/data/modules/profile.js
  extension/data/modules/trouble.js
  extension/data/modules/usernotes.js
  extension/data/tbcore.js
  extension/data/tbhelpers.js
  extension/data/tbui.js
Labels: code quality

#278 Fix macro distinguish feedback
  extension/data/modules/macros.js
Labels: bug

#268 fix(Config): Edit old RR defaults remove for posts
  extension/data/modules/config.js
Labels: bug

#270 Fix settings backup button
  extension/data/tbcore.js
  extension/data/tbmodule.js
Labels: bug, core: tbmodule

#277 Always send a spam parameter
  extension/data/tbapi.js
Labels: bug, module: commentnuke

#267 Read version name in about page from manifest
  extension/data/tbcore.js
  extension/data/tbmodule.js
Labels: code quality

#279 fix(RR): Changed comment RR behaviour
  extension/data/modules/removalreasons.js
Labels: module: removalreasons

#250 Convert $.ajax() to fetch()
  extension/data/background/handlers/webrequest.js
  extension/data/modules/historybutton.js
  extension/data/modules/modbutton.js
  extension/data/modules/modmatrix.js
  extension/data/modules/notifier.js
  extension/data/tbapi.js
  extension/data/tbcore.js
Labels: code quality, core: background
