Repository toolbox-team/reddit-moderator-toolbox, pull requests merged in 2024-03, with the labels that each got.

#893 Fix for #498
  extension/data/tbplugins.js
Labels: bug, module: queuetools

#912 Use material icon for setting link indication
  extension/data/styles/modbar.css
Labels: enhancement

#913 Remove unused support code for old dev console
  extension/data/modules/modbar.js
  extension/data/styles/modbar.css
  extension/data/styles/toolbox.css
Labels: code quality

#915 Remove old Modmail Pro module
  extension/data/init.ts
  extension/data/modules/modbar.js
  extension/data/modules/modmailpro.js
  extension/data/modules/notifier.js
  extension/data/styles/modbar.css
  extension/data/styles/notifier.css
  extension/data/tbconstants.ts
Labels: needs public docs, feature deletion

#917 Bringing back beta builds, baby
  .github/workflows/publish-beta.yml
  .github/workflows/publish-stable.yml
  CONTRIBUTING.md
  extension/chrome_manifest.json
  extension/data/init.ts
  extension/data/modules/achievements.js
  extension/data/modules/modbar.js
  extension/data/modules/modnotes.jsx
  extension/data/modules/queuetools.js
  extension/data/modules/support.js
  extension/data/styles/modbar.css
  extension/data/tbconstants.ts
  extension/data/tbcore.js
  extension/data/tbmodule.jsx
  extension/firefox_manifest.json
  package.json
  release.mjs
  rollup.config.js
Labels: enhancement, meta

#921 Fix reload button position in queue overlay
  extension/data/styles/queue_overlay.css
Labels: bug, module: queue overlay

#922 Fix misc. deepscan issues
  extension/data/components/PageNotificationContainer.tsx
  extension/data/components/ProgressivePager.tsx
  extension/data/tbmodule.jsx
Labels: code quality

#914 Fix logic for adding the modnotes window to the DOM
  extension/data/components/Window.tsx
  extension/data/modules/modnotes.jsx
Labels: bug, module: modnotes

#916 Refactor platform/login detection and add *extremely* basic Shreddit support
  extension/data/init.ts
  extension/data/modules/comment.js
  extension/data/modules/macros.js
  extension/data/modules/queue_overlay.js
  extension/data/tbcore.js
  extension/data/util/platform.ts
Labels: enhancement, code quality, platform: shreddit

#920 Add dedicated icon for beta builds
  .github/workflows/publish-beta.yml
  extension/data/images/beta_icon128.png
  extension/data/images/beta_icon16.png
  extension/data/images/beta_icon256.png
  extension/data/images/beta_icon48.png
  extension/data/images/beta_logo_vector.svg
Labels: meta
