Repository toolbox-team/reddit-moderator-toolbox, pull requests merged in 2024-10, with the labels that each got.

#999 bump @types/webextension-polyfill@0.12.1
  extension/data/components/PageNotificationContainer.tsx
  extension/data/tbapi.ts
  package-lock.json
  package.json
Labels: dependencies

#1001 ignore module-level directive warnings about `"use client";`
  rollup.config.js
Labels: code quality, meta

#1002 store notification metadata in individual keys to avoid races
  extension/data/background/handlers/notifications.js
Labels: bug, module: notifier, core: background

#1000 Slightly improve logging around failed init conditions
  extension/data/init.ts
  tsconfig.json
Labels: code quality, core: init

#992 Fix per-user cache storage keys
  extension/data/background/handlers/cache.js
Labels: bug, core: tbstorage

#1008 Re-add CSS for settings "About" page
  extension/data/styles/modbar.css
  extension/data/tbmodule.jsx
  extension/data/tbmodule.module.css
Labels: bug, core: tbmodule

#1010 Fix for Beta/Developer builds of Opera
  extension/data/tbcore.js
Labels: bug
